# Generated by Django 5.0.3 on 2024-03-29 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='tickets/')),
                ('status', models.CharField(choices=[('unpaid', 'ยังไม่ชำระเงิน'), ('pending', 'รอการตรวจสอบ'), ('paid', 'ชำระเงินสำเร็จ')], default='unpaid', max_length=20)),
                ('add_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.addroutes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
