# Generated by Django 5.0.3 on 2024-03-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
