# Generated by Django 5.0.3 on 2024-04-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_ticket_ticket_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='img',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
    ]
