# Generated by Django 5.0.3 on 2024-04-01 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_ticket_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_no',
        ),
    ]
