# Generated by Django 5.0.3 on 2024-04-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_ticket_ticket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
