# Generated by Django 5.0.3 on 2024-04-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_ticket_car_alter_ticket_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='car',
        ),
    ]
