# Generated by Django 5.0.3 on 2024-04-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_ticket_statusapprove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='statusApprove',
            field=models.CharField(choices=[('reject', 'ไม่อนุมัติ'), ('approve', 'อนุมติ'), ('pending', 'รอดำเนินกาาร')], default='pending', max_length=20),
        ),
    ]
