# Generated by Django 5.0.3 on 2024-04-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_remove_addroutes_carnumber_remove_addroutes_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroutes',
            name='max_seat',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='addroutes',
            name='status',
            field=models.CharField(choices=[('available', 'ว่าง'), ('unavailable', 'ไม่ว่าง')], default='available', max_length=20),
        ),
    ]
