# Generated by Django 5.0.3 on 2024-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'ว่าง'), ('unavailable', 'ไม่ว่าง')], default='available', max_length=20),
        ),
    ]
