# Generated by Django 5.0.3 on 2024-03-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('unavailable', 'ไม่ว่าง'), ('available', 'ว่าง')], default='unavailable', max_length=20),
        ),
    ]
