# Generated by Django 5.0.3 on 2024-04-01 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_seat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car'),
        ),
    ]
