# Generated by Django 5.0.3 on 2024-04-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_seat_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('unavailable', 'ไม่ว่าง'), ('available', 'ว่าง')], default='available', max_length=20),
        ),
    ]
