# Generated by Django 5.0.3 on 2024-04-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_seat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='driver',
        ),
    ]
